title: Michael Jacob
description: I'm a student at the University of Pennsylvania studying Mathematics and Computer Science. I am interested in geometric deep learning, generative modeling, and 3D perception with an emphasis on principled generation. 

Projects:

Coming soon 


